### ISSUE TITLE
Is it possible to play content with HDCP enabled?

### ISSUE THREAD

**Issue by mifricken** [darwinvtomy/drm_wv_fp_player#5]
Hello, thanks for the amazing plugin.
But Im getting this error with a Widevine/HDCP content:

I/OMXClient(21178): IOmx service obtained
I/ACodec  (21178): In onAllocateComponent create compenent, codec name: OMX.hisi.video.decoder.avc.secure
D/SurfaceUtils(21178): connecting to surface 0x76de46c010, reason connectToSurface
I/MediaCodec(21178): [OMX.hisi.video.decoder.avc.secure] setting surface generation to 21686284
D/SurfaceUtils(21178): disconnecting from surface 0x76de46c010, reason connectToSurface(reconnect)
D/SurfaceUtils(21178): connecting to surface 0x76de46c010, reason connectToSurface(reconnect)
E/ACodec  (21178): [OMX.hisi.video.decoder.avc.secure] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
I/HwExtendedCodec(21178): mime is [video/avc] at setVideoFormat
I/ACodec  (21178): codec does not support config priority (err -22)
I/ACodec  (21178): [OMX.hisi.video.decoder.avc.secure] got color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) err=0(NO_ERROR)
I/ACodec  (21178): [OMX.hisi.video.decoder.avc.secure] got color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) err=0(NO_ERROR)
I/ACodec  (21178): [OMX.hisi.video.decoder.avc.secure] using color aspects (R:2(Limited), P:1(BT709_5), M:1(BT709_5), T:3(SMPTE170M)) and dataspace 0x104
I/ACodec  (21178): onStart
D/SurfaceUtils(21178): disconnecting from surface 0x76de46c010, reason setNativeWindowSizeFormatAndUsage
D/SurfaceUtils(21178): connecting to surface 0x76de46c010, reason setNativeWindowSizeFormatAndUsage
E/SurfaceUtils(21178): native window cannot handle protected buffers: the consumer should either be a hardware composer or support hardware protection
E/ACodec  (21178): Failed to allocate buffers after transitioning to IDLE state (error 0xffffffff)
E/ACodec  (21178): signalError(omxError 0x80001001, internalError -1)
E/MediaCodec(21178): Codec reported err 0xffffffff, actionCode 0, while in state 5
D/SurfaceUtils(21178): disconnecting from surface 0x76de46c010, reason disconnectFromSurface
E/ACodec  (21178): [OMX.hisi.video.decoder.avc.secure] ERROR(0x80001012)
E/ACodec  (21178): signalError(omxError 0x80001012, internalError -2147483648)
E/ACodec  (21178): [OMX.hisi.video.decoder.avc.secure] ERROR(0x80001012)
E/ACodec  (21178): signalError(omxError 0x80001012, internalError -2147483648)
E/MediaCodec(21178): Codec reported err 0x80001012, actionCode 0, while in state 10
E/MediaCodec(21178): Codec reported err 0x80001012, actionCode 0, while in state 10
W/MediaCodecRenderer(21178): Failed to initialize decoder: OMX.hisi.video.decoder.avc.secure
W/MediaCodecRenderer(21178): android.media.MediaCodec$CodecException: start failed
W/MediaCodecRenderer(21178): 	at android.media.MediaCodec.native_start(Native Method)
W/MediaCodecRenderer(21178): 	at android.media.MediaCodec.start(MediaCodec.java:2075)
W/MediaCodecRenderer(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:814)
W/MediaCodecRenderer(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer(21178): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer(21178): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer(21178): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer(21178): 	at android.os.Handler.dispatchMessage(Handler.java:108)
W/MediaCodecRenderer(21178): 	at android.os.Looper.loop(Looper.java:216)
W/MediaCodecRenderer(21178): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(21178): Playback error.
E/ExoPlayerImplInternal(21178): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.hisi.video.decoder.avc.secure, Format(stream_4, null, null, video/avc, avc1.64001f, 3000000, null, [1280, 720, 29.97003], [-1, -1])
E/ExoPlayerImplInternal(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal(21178): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal(21178): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal(21178): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal(21178): 	at android.os.Handler.dispatchMessage(Handler.java:108)
E/ExoPlayerImplInternal(21178): 	at android.os.Looper.loop(Looper.java:216)
E/ExoPlayerImplInternal(21178): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(21178): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.hisi.video.decoder.avc.secure, Format(stream_4, null, null, video/avc, avc1.64001f, 3000000, null, [1280, 720, 29.97003], [-1, -1])
E/ExoPlayerImplInternal(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal(21178): 	... 9 more
E/ExoPlayerImplInternal(21178): Caused by: android.media.MediaCodec$CodecException: start failed
E/ExoPlayerImplInternal(21178): 	at android.media.MediaCodec.native_start(Native Method)
E/ExoPlayerImplInternal(21178): 	at android.media.MediaCodec.start(MediaCodec.java:2075)
E/ExoPlayerImplInternal(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:814)
E/ExoPlayerImplInternal(21178): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal(21178): 	... 10 more
W/InputMethodManager(21178): startInputReason = 8

Thanks!

**Comment by darwinvtomy** [comment]
Hi, Sorry for late reply.  Have you checked the Native Exoplayer app with the same device ? May be your device might not be HDCP compilent. Please  do let me know once you checked it. There could be some issues with WIDEVINE license . If there any problem persist try updating your mobile from OEM test it again.Please do let me know if it is fixed
